Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"

  # Public network
  config.vm.network "public_network"

  # Resources
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
    vb.cpus = 2
  end
end
