---
- name: Install fail2ban
  apt:
    name: fail2ban
    state: present
  become: yes

- name: Copy fail2ban jail.local
  copy:
    src: ssh/jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Ensure fail2ban is started and enabled
  service:
    name: fail2ban
    state: started
    enabled: true
  become: yes